-- Migration: Create ch_churn_alerts table
-- Tracks churn risk alerts generated by the health score engine

CREATE TABLE IF NOT EXISTS ch_churn_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES ch_clients(id) ON DELETE CASCADE,

  -- Alert details
  priority TEXT NOT NULL CHECK (priority IN ('critical', 'medium', 'low')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
  trigger_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,

  -- Metric context
  metric_name TEXT,
  metric_value NUMERIC,
  threshold_value NUMERIC,

  -- Notification tracking
  slack_sent BOOLEAN DEFAULT FALSE,
  slack_sent_at TIMESTAMPTZ,
  email_sent BOOLEAN DEFAULT FALSE,
  email_sent_at TIMESTAMPTZ,

  -- Resolution tracking
  acknowledged_by TEXT,
  acknowledged_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_ch_alerts_client ON ch_churn_alerts(client_id);
CREATE INDEX idx_ch_alerts_status ON ch_churn_alerts(status);
CREATE INDEX idx_ch_alerts_priority ON ch_churn_alerts(priority);
CREATE INDEX idx_ch_alerts_trigger ON ch_churn_alerts(trigger_type);
CREATE INDEX idx_ch_alerts_created ON ch_churn_alerts(created_at DESC);

-- Deduplication index: prevent same trigger for same client within recent timeframe
CREATE INDEX idx_ch_alerts_dedup ON ch_churn_alerts(client_id, trigger_type, created_at DESC);

-- RLS
ALTER TABLE ch_churn_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read" ON ch_churn_alerts
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated insert" ON ch_churn_alerts
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated update" ON ch_churn_alerts
  FOR UPDATE TO authenticated USING (true);

-- Updated at trigger
CREATE TRIGGER ch_churn_alerts_updated_at
  BEFORE UPDATE ON ch_churn_alerts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE ch_churn_alerts;
